return {
PlaceObj('ModItemCode', {
	'name', "Templates",
	'CodeFileName', "Code/Templates.lua",
}),
PlaceObj('ModItemCode', {
	'name', "ModItems",
	'CodeFileName', "Code/ModItems.lua",
}),
PlaceObj('ModItemCode', {
	'name', "SurvivorModification",
	'CodeFileName', "Code/SurvivorModification.lua",
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ApplyWhen",
	'DisplayName', "Apply When",
	'Help', "When this mod should make changes to survivors.",
	'DefaultValue', "Survivor Joins & new game",
	'ChoiceList', {
		"Survivor Joins & new game",
		"On Game Load",
		"New+Load Game, Survivor Joins",
		"Never (disable mod)",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ApplyTo",
	'DisplayName', "Apply To",
	'Help', "Which survivors to apply the changes to.",
	'DefaultValue', "*All Survivors*",
	'ChoiceList', {
		"*All Survivors*",
		"Anette Falcov",
		"Carter Grodre",
		"Connor Dryce",
		"Daniel Shanks",
		"Edmund Grodre",
		"Ember Griffin",
		"Emelin Leth",
		"Greyson Valk",
		"Hann Tae",
		"Henry Caldwell",
		"Hope 9000",
		"Hugo Delano",
		"Jack Davies",
		"Jayla Lohen",
		"Kana Itoh",
		"Katina Yul",
		"Ken Laux",
		"Krista Yul",
		"Laara Falcov",
		"Maki Onda",
		"Melody Adeyemi",
		"Naras Ledi",
		"Nova Sones",
		"Paulette Marota",
		"Quin Windu",
		"Rakha Chad",
		"Rita Ibori",
		"Samantha Craft",
		"Simon Frummos",
		"Sora Satoh",
		"Talas Wabell",
		"Umayr Bozeri",
		"Vanessa Valk",
		"Vicente Santiago",
		"Vivien Bozeri",
		"Yokko Dokuchi",
		"Zander Norrig",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "_DisplayFormatting_Gap1",
	'comment', "Display formatting only",
	'DisplayName', "`",
	'Help', "Display formatting only",
	'DisplayColor', RGBA(20, 20, 20, 255),
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllSkillsAction",
	'DisplayName', "*All Skills*",
	'Help', "Change the value for every skill.   Will be overriden by individual skill options set below e.g Combat",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "AllSkillsValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "`",
	'Help', "All skills value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllSkillsInclination",
	'DisplayName', "*All Skills* Inclination",
	'Help', "Change the inclination for every skill.   Will be overriden by any inclination options set below e.g Combat Inclination.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CombatAction",
	'DisplayName', "Combat",
	'Help', "The physical strength and accuracy of the survivor. Affects targeting speed and chance to hit in combat.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "CombatValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Combat",
	'Help', "Combat value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CombatInclination",
	'DisplayName', "Combat Inclination",
	'Help', "The physical strength and accuracy of the survivor. Affects targeting speed and chance to hit in combat.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ConstructionAction",
	'DisplayName', "Construction",
	'Help', "The ability to construct enduring structures. Affects construction speed and the likelihood of construction sites to fall apart. Allows the construction of more advanced buildings.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "ConstructionValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Construction",
	'Help', "Construction value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ConstructionInclination",
	'DisplayName', "Construction Inclination",
	'Help', "The ability to construct enduring structures. Affects construction speed and the likelihood of construction sites to fall apart. Allows the construction of more advanced buildings.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CookingAction",
	'DisplayName', "Cooking",
	'Help', "The ability to efficiently cook complex recipes. Experienced cooks can produce more complex food items, quicker and with far less chance to overcook the meal.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "CookingValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Cooking",
	'Help', "Cooking value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CookingInclination",
	'DisplayName', "Cooking Inclination",
	'Help', "The ability to efficiently cook complex recipes. Experienced cooks can produce more complex food items, quicker and with far less chance to overcook the meal.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CraftingAction",
	'DisplayName', "Crafting",
	'Help', "The ability to efficiently craft complex items. Affects the crafting speed and the chance to damage or destroy the crafted item. Allows the crafting of more complex items.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "CraftingValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Crafting",
	'Help', "Crafting value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CraftingInclination",
	'DisplayName', "Crafting Inclination",
	'Help', "The ability to efficiently craft complex items. Affects the crafting speed and the chance to damage or destroy the crafted item. Allows the crafting of more complex items.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FarmingAction",
	'DisplayName', "Farming",
	'Help', "The ability to take care of plants and animals. Experienced farmers can handle more advanced crops and harvest plants quicker and with less chance to lose the harvest in the process.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "FarmingValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Farming",
	'Help', "Farming value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FarmingInclination",
	'DisplayName', "Farming Inclination",
	'Help', "The ability to take care of plants and animals. Experienced farmers can handle more advanced crops and harvest plants quicker and with less chance to lose the harvest in the process.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "HealingAction",
	'DisplayName', "Healing",
	'Help', "The ability to treat various health conditions. Experienced doctors can provide better health treatments, quicker and with a higher success rate.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "HealingValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Healing",
	'Help', "Healing value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "HealingInclination",
	'DisplayName', "Healing Inclination",
	'Help', "The ability to treat various health conditions. Experienced doctors can provide better health treatments, quicker and with a higher success rate.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "PhysicalAction",
	'DisplayName', "Physical",
	'Help', "The physical ability of the survivor. It affects the speed with which the survivor performs activities such as Scavenging, Mining and Cutting.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "PhysicalValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Physical",
	'Help', "Physical value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "PhysicalInclination",
	'DisplayName', "Physical Inclination",
	'Help', "The physical ability of the survivor. It affects the speed with which the survivor performs activities such as Scavenging, Mining and Cutting.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "IntellectualAction",
	'DisplayName', "Intellect",
	'Help', "The intellectual potential of the survivor. It affects the speed at which the survivor researches new technologies and observes unknown species.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "IntellectualValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "Intellect",
	'Help', "Intellect value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "IntellectualInclination",
	'DisplayName', "Intellect Inclination",
	'Help', "The intellectual potential of the survivor. It affects the speed at which the survivor researches new technologies and observes unknown species.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "_DisplayFormatting_Gap2",
	'comment', "Display formatting only",
	'DisplayName', "`",
	'Help', "Display formatting only",
	'DisplayColor', RGBA(20, 20, 20, 255),
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllTraitsAction",
	'DisplayName', "*All Traits*",
	'Help', "Add or remove all traits on survivors.   Will be overridden by any individual trait options set below e.g Hardworking.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AdvancedLearningAlgorithms",
	'DisplayName', "Advanced learning algorithms",
	'Help', "Gains 50% more experience from doing tasks",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Agoraphobia",
	'DisplayName', "Agoraphobia",
	'Help', "Has increased Manipulation efficiency and Happiness while inside, which are decreased outside",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Agrizoophobic",
	'DisplayName', "Agrizoophobic",
	'Help', "Will not harvest or take care of plants and animals in any circumstances",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AnimalTamer",
	'DisplayName', "Animal tamer",
	'Help', "Never fails taming attempts",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AntifreezeBlood",
	'DisplayName', "Antifreeze blood",
	'Help', "Tolerances to cold and heat are increased by 10°C",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ConstructionInstructor",
	'DisplayName', "Architecture instructor",
	'Help', "Occasionally improves the Construction skill of others",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AvidCarpenter",
	'DisplayName', "Avid carpenter",
	'Help', "4x work speed when crafting or constructing stuff with wood",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AvidFarmer",
	'DisplayName', "Avid farmer",
	'Help', "Seeds and harvests plants twice as fast",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AvidTailor",
	'DisplayName', "Avid tailor",
	'Help', "4x work speed when crafting stuff from fabrics or leather",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "BadMemory",
	'DisplayName', "Bad memory",
	'Help', "Learns skills slower.  Incompatible with: Fast learner",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Bloodlust",
	'DisplayName', "Bloodlust",
	'Help', "Gains Happiness when killing or observing death.  Incompatible with: Pacifist, Liberated",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Calming",
	'DisplayName', "Calming",
	'Help', "Tries to calm down others regardless of own opinion of them; has increased chance to succeed",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Cheerful",
	'DisplayName', "Cheerful personality",
	'Help', "Has permanently increased Happiness.  Incompatible with: Gloomy personality, Neurotic personality, Liberated",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CloseCombatSpecialist",
	'DisplayName', "Close combat specialist",
	'Help', "Fights twice as fast with melee weapons",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Clumsy",
	'DisplayName', "Clumsy",
	'Help', "Will not do crafting tasks; Movement speed is decreased by 10%",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CognitiveStabilizers",
	'DisplayName', "Cognitive stabilizers",
	'Help', "Cannot experience Meltdowns or Euphoria",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CombatInstructor",
	'DisplayName', "Combat instructor",
	'Help', "Occasionally improves the Combat skill of others",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Attentive",
	'DisplayName', "Compassionate",
	'Help', "Makes others happy by cheering them up",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ConstructionDatabase",
	'DisplayName', "Construction database",
	'Help', "3x work speed when constructing structures or devices; Gains Sentience while constructing stuff",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CookingRecipesDatabase",
	'DisplayName', "Cooking recipes database",
	'Help', "5x work speed when cooking; Gains Sentience while cooking",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CraftingAttachments",
	'DisplayName', "Crafting attachments",
	'Help', "Manipulation efficiency is increased by 100%",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CraftingDatabase",
	'DisplayName', "Crafting database",
	'Help', "3x work speed when crafting, tailoring or assembling electronics; Gains Sentience while crafting",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CraftingInstructor",
	'DisplayName', "Crafting teacher",
	'Help', "Occasionally improves the Crafting skill of others",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "DesertDweller",
	'DisplayName', "Desert born",
	'Help', "Tolerances to cold and heat are increased by 10°C",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "DynamicResponseNanoflesh",
	'DisplayName', "Dynamic response nanoflesh",
	'Help', "+200 Integrity; Recovers Integrity twice as fast",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Engineer",
	'DisplayName', "Engineer",
	'Help', "3x work speed when constructing devices or furniture",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "EntertainmentJunkie",
	'DisplayName', "Entertainment junkie",
	'Help', "Needs to relax twice as often, requires higher variety of entertainments",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ExperiencedScavenger",
	'DisplayName', "Experienced scavenger",
	'Help', "Finds twice more Scrap metal during scavenge operations and expeditions",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Explorer",
	'DisplayName', "Explorer",
	'Help', "Loves going on expeditions, expeditions take less time",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ExcquisiteCook",
	'DisplayName', "Exquisite cook",
	'Help', "Makes even the simplest dishes taste exquisite",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FarmingInstructor",
	'DisplayName', "Farm teacher",
	'Help', "Occasionally improves the Farming skill of others",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FarmingDatabase",
	'DisplayName', "Farming database",
	'Help', "3x work speed when planting and harvesting crops, or when taking care of animals; Gains Sentience while doing those activities",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FastLearner",
	'DisplayName', "Fast learner",
	'Help', "Learns skills twice as fast.  Incompatible with: Bad memory",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "FastWalker",
	'DisplayName', "Fast walker",
	'Help', "Movement speed is increased by 25%.  Incompatible with: Slowpoke",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "GatherersDatabase",
	'DisplayName', "Gatherer's database",
	'Help', "3x work speed when mining, chopping trees or salvaging; Gains Sentience while doing these activities",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Genius",
	'DisplayName', "Genius",
	'Help', "Has occasional insights that boost the current research progress",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Gloomy",
	'DisplayName', "Gloomy personality",
	'Help', "Has permanently decreased Happiness.  Incompatible with: Cheerful personality, Neurotic personality, Liberated",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Glutton",
	'DisplayName', "Glutton",
	'Help', "Gets hungry 25% quicker.  Incompatible with: Light eater",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Haggler",
	'DisplayName', "Haggler",
	'Help', 'While in the colony, all trade ships sell goods at 5% discount and buy them at 5% higher price; Can negotiate decreased payment of workers ("Trading Outpost" scenario)',
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Hardworking",
	'DisplayName', "Hardworking",
	'Help', "Has 25% more Movement speed and Manipulation efficiency.  Incompatible with: Neurotic personality",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Healthy",
	'DisplayName', "Healthy",
	'Help', "+100 Health; Recovers Health twice as fast.  Incompatible with: Sickly",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Hemophobia",
	'DisplayName', "Hemophobia",
	'Help', "Can't perform Healing tasks",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Idiot",
	'DisplayName', "Idiot",
	'Help', "Can't perform Intellectual tasks",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ImpeccableHealer",
	'DisplayName', "Impeccable healer",
	'Help', "Can't fail a medical treatment",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "InspirationalWriter",
	'DisplayName', "Inspirational writer",
	'Help', "Relaxes by writing short stories that inspire others when read",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Intimidating",
	'DisplayName', "Intimidating",
	'Help', "Occasionally intimidates others, making them feel unease",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "KitchenHazard",
	'DisplayName', "Kitchen hazard",
	'Help', "Can't perform Cooking tasks",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Hope",
	'DisplayName', "Learning AI",
	'Help', "Begins with limited capabilities in most activities, but gradually develops new abilities and traits through the accumulation of skill experience.",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Liberated",
	'DisplayName', "Liberated",
	'Help', "Cannot experience Meltdowns or Euphoria.  Incompatible with: Neurotic personality, Bloodlust, Cheerful personality, Gloomy personality",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "LowBleedHydraulics",
	'DisplayName', "Low-bleed hydraulics",
	'Help', "Oil bleeding is permanently decreased by 10 Integrity per hour",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "MasterBuilder",
	'DisplayName', "Master builder",
	'Help', "Constructs structures and devices twice as fast",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "MasterHunter",
	'DisplayName', "Master hunter",
	'Help', "Has 25% chance to deal kill shot while hunting prey (100% when the prey is unaware)",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "HealingDatabase",
	'DisplayName', "Medicine database",
	'Help', "5x work speed when healing human or animal patients; Gains Sentience while healing",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "MusicalProdigy",
	'DisplayName', "Musical prodigy",
	'Help', "Makes others happy when playing music.  Incompatible with: Tone-deaf",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "NaturalCuriosity",
	'DisplayName', "Natural curiosity",
	'Help', "Has chance to field observe unknown species during expeditions",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "NaturalLeader",
	'DisplayName', "Natural leader",
	'Help', "Occasionally motivates others increasing their Manipulation efficiency",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Neurotic",
	'DisplayName', "Neurotic personality",
	'Help', "Manipulation efficiency is increased by 50%.  Incompatible with: Hardworking, Gloomy personality, Cheerful personality, Liberated",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "NightOwl",
	'DisplayName', "Night owl",
	'Help', "Gains Happiness while awake at night",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Obtuse",
	'DisplayName', "Obtuse",
	'Help', "Will not do research or observation tasks",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Pacifist",
	'DisplayName', "Pacifist",
	'Help', "Will not fight or hunt in any circumstances.  Incompatible with: Bloodlust, Sniper eye",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Prospector",
	'DisplayName', "Prospector",
	'Help', "10% chance to find Ore when mining",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "QuickSleeper",
	'DisplayName', "Quick sleeper",
	'Help', "Rests twice as fast.  Incompatible with: Sleepy",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ResearchAlgorithms",
	'DisplayName', "Research algorithms",
	'Help', "Has occasional insights that boost the current research progress; Insights grant additional Intellect experience",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Sickly",
	'DisplayName', "Sickly",
	'Help', "Recovers Health twice as slow.  Incompatible with: Healthy, Thrombophilia",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Sleepy",
	'DisplayName', "Sleepy",
	'Help', "Rests twice as slow.  Incompatible with: Quick sleeper",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Slowpoke",
	'DisplayName', "Slowpoke",
	'Help', "Movement speed is decreased by 25%.  Incompatible with: Fast walker",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "SniperEye",
	'DisplayName', "Sniper eye",
	'Help', "Shoots twice as fast with ranged weapons.  Incompatible with: Pacifist",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "SniperLenses",
	'DisplayName', "Sniper lenses",
	'Help', "Shoots twice as fast with ranged weapons",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Jayla_SplitPersonality",
	'DisplayName', "Split personality",
	'Help', "Occasionally switches traits with an alter-ego",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "SwiftStrikeGears",
	'DisplayName', "Swift strike gears",
	'Help', "Fights twice as fast with melee weapons",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "TacticalCommander",
	'DisplayName', "Tactical commander",
	'Help', "Increases the hit chance and the critical hit chance of everyone in 50 m range by 10%",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CoagulatedBlood",
	'DisplayName', "Thrombophilia",
	'Help', "Bleeding is permanently decreased by 5 Health per hour.  Incompatible with: Sickly",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ToneDeaf",
	'DisplayName', "Tone-deaf",
	'Help', "Makes others unhappy when playing music.  Incompatible with: Musical prodigy",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Vegetarian",
	'DisplayName', "Vegetarian",
	'Help', "Refuses to eat meat",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "VelocityEnhancers",
	'DisplayName', "Velocity enhancers",
	'Help', "Movement speed is increased by 50%",
	'DefaultValue', "<color 20 20 20 255>Don't change</color>",
	'ChoiceList', {
		"<color 20 20 20 255>Don't change</color>",
		"Add",
		"Remove",
	},
}),
}
