return {
PlaceObj('ModItemCode', {
	'CodeFileName', "Code/Templates.lua",
}),
PlaceObj('ModItemCode', {
	'CodeFileName', "Code/Script.lua",
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ApplyWhen",
	'DisplayName', "Apply When",
	'Help', "When this mod should make changes to survivors.",
	'DefaultValue', "Survivor Joins & new game",
	'ChoiceList', {
		"Survivor Joins & new game",
		"On Game Load",
		"Never (disable mod)",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "ApplyTo",
	'DisplayName', "Apply To",
	'Help', "Which survivors to apply the changes to.",
	'DefaultValue', "All Survivors",
	'ChoiceList', {
		"All Survivors",
		"Nobody (disable mod)",
		"Dick",
		"Jane",
		"Harry",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "_DisplayFormatting_Gap1",
	'comment', "Display formatting only",
	'DisplayName', "`",
	'Help', "Display formatting only",
	'DisplayColor', RGBA(20, 20, 20, 255),
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllSkillsAction",
	'DisplayName', "*All Skills*",
	'Help', "Change the value of all skills in this way using the value set below.   Overriden by specific skill value changes if set below (e.g Combat).",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "AllSkillsValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "`",
	'Help', "All skills value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllSkillsInclination",
	'DisplayName', "*All Skills* Inclination",
	'Help', "Change the inclination for every skill.   Will be overriden by any inclination options set below e.g Combat Inclination.",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CombatAction",
	'DisplayName', "Combat",
	'Help', "say what it does",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Set to:",
		"Set to Minimum of:",
		"Set to Maximum of:",
	},
}),
PlaceObj('ModItemOptionNumber', {
	'name', "CombatValue",
	'NameColor', RGBA(191, 183, 175, 255),
	'DisplayName', "`",
	'Help', "Combat value. Used by option above.",
	'DisplayColor', RGBA(20, 20, 20, 255),
	'DefaultValue', 3,
	'MaxValue', 10,
}),
PlaceObj('ModItemOptionChoice', {
	'name', "CombatInclination",
	'DisplayName', "Combat Inclination",
	'Help', "say what it does",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Set to Interested",
		"Set to Normal",
		"Set to Indifferent",
		"Change Indifferent to Normal",
		"Change Interested to Normal",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "_DisplayFormatting_Gap2",
	'comment', "Display formatting only",
	'DisplayName', "`",
	'Help', "Display formatting only",
	'DisplayColor', RGBA(20, 20, 20, 255),
}),
PlaceObj('ModItemOptionChoice', {
	'name', "AllTraitsAction",
	'DisplayName', "*All Traits*",
	'Help', "Add or remove all traits on survivors.   Will be overridden by any individual trait options set below e.g Hardworking.",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Remove",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "Hardworking",
	'DisplayName', "Hardworking",
	'Help', "say what it does",
	'DefaultValue', "Don't change",
	'ChoiceList', {
		"Don't change",
		"Add",
		"Remove",
	},
}),
}
